### ISSUE TITLE
Is anyone having this issue?

### ISSUE THREAD

**Issue by briviere** [mulesoft/raml-client-generator#21]
Used a more complicated RAML contract and it is crashing with the following:

s.1.raml -o api-client -l javascript
part:/{keyType}{key}
spec:[object Object]
key:undefined
TypeError: Cannot read property 'relativeUri' of undefined
    at recurse (/home/briviere/.npm-packages/lib/node_modules/raml-client-generator/node_modules/raml-generator/lib/context/resources.js:113:58)
    at attachResource (/home/briviere/.npm-packages/lib/node_modules/raml-client-generator/node_modules/raml-generator/lib/context/resources.js:158:3)
    at /home/briviere/.npm-packages/lib/node_modules/raml-client-generator/node_modules/raml-generator/lib/context/resources.js:149:9
    at Array.forEach (native)
    at recurse (/home/briviere/.npm-packages/lib/node_modules/raml-client-generator/node_modules/raml-generator/lib/context/resources.js:148:26)
    at recurse (/home/briviere/.npm-packages/lib/node_modules/raml-client-generator/node_modules/raml-generator/lib/context/resources.js:140:14)
    at recurse (/home/briviere/.npm-packages/lib/node_modules/raml-client-generator/node_modules/raml-generator/lib/context/resources.js:140:14)
    at attachResource (/home/briviere/.npm-packages/lib/node_modules/raml-client-generator/node_modules/raml-generator/lib/context/resources.js:158:3)
    at /home/briviere/.npm-packages/lib/node_modules/raml-client-generator/node_modules/raml-generator/lib/context/resources.js:187:12
    at Array.forEach (native)

**Comment by blakeembrey** [comment]
@briviere I'll take a look into it, can you give me the version you're using and maybe a sample RAML file that replicates the issue?

**Comment by briviere** [comment]
Version 0.1.1

Sure I can work on providing the raml and related JSON Schema.

Brian
