### ISSUE TITLE
RAML 1.0 support

### ISSUE THREAD

**Issue by DevWurm** [mulesoft/raml-client-generator#26]
Please support RAML 1.0. This would be great.

**Comment by meetmangukiya** [comment]
Yes, please add support for 1.0

**Comment by sichvoge** [comment]
As the only client that has been added is JavaScript so far, I guess you are using this one right?

If the answer is yes, RAML 1.0 is already supported. We haven't done some work on this for a long time due to prioritization, but you can report issues of course.

**Comment by kheide** [comment]
@sichvoge are you sure?

raml-to-client specs/api-gw.raml -o clients/api-gw-sdk -l javascript
YAMLError: Unsupported RAML version: '#%RAML 1.0'

**Comment by nek4life** [comment]
Same error as above

YAMLError: Unsupported RAML version: '#%RAML 1.0'
    at _Class.Scanner.Scanner.scan_to_next_token (/usr/local/lib/node_modules/raml-client-generator/node_modules/raml-parser/lib/scanner.js:720:21)
    at _Class.Scanner.Scanner.fetch_more_tokens (/usr/local/lib/node_modules/raml-client-generator/node_modules/raml-parser/lib/scanner.js:183:12)
    at _Class.Scanner.Scanner.check_token (/usr/local/lib/node_modules/raml-client-generator/node_modules/raml-parser/lib/scanner.js:122:14)
    at _Class.Parser.Parser.parse_implicit_document_start (/usr/local/lib/node_modules/raml-client-generator/node_modules/raml-parser/lib/parser.js:126:17)
    at _Class.Parser.Parser.check_event (/usr/local/lib/node_modules/raml-client-generator/node_modules/raml-parser/lib/parser.js:62:48)
    at _Class.Composer.Composer.getYamlRoot (/usr/local/lib/node_modules/raml-client-generator/node_modules/raml-parser/lib/composer.js:60:17)
    at /usr/local/lib/node_modules/raml-client-generator/node_modules/raml-parser/lib/raml.js:226:23
    at Promise.apply (/usr/local/lib/node_modules/raml-client-generator/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/raml-client-generator/node_modules/q/q.js:752:41)
    at /usr/local/lib/node_modules/raml-client-generator/node_modules/q/q.js:1337:14
